TE-496 connect and disconnect
test-editor/host-fixture pull request #1
Opened 2017-05-17 12:00 UTC by kbayraktar

2017-05-17 13:04 UTC, franzbecker requested changes
The code needs some cleanup as indicated by the comments. Also a Jenkinsfile and unit tests are missing.

2017-05-17 13:04 UTC, franzbecker commented on .gitignore
> +# Java build artifacts class files
Please provide a `.gitignore` that is the same as in the other fixtures. See https://github.com/test-editor/rest-fixture/blob/develop/.gitignore

2017-05-17 13:04 UTC, franzbecker commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
We don't want to check in Eclipse specific stuff in the fixtures. See comment to `.gitignore`

2017-05-17 13:04 UTC, franzbecker commented on build.gradle
> +plugins {
Please use a `build.gradle` that is similar to the existing ones. If each fixture starts writing its build.gradle from scratch they all differ. See https://github.com/test-editor/rest-fixture/blob/develop/build.gradle

2017-05-17 13:04 UTC, franzbecker commented on settings.gradle
> +/*
Please remove those comments

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.aml
> +    template = "Connect to " ${hostname} " with path " s3270Path " and port " ${port}
The spaces in the template are not necessary. Please write `"Connect to" ${hostname} "with path"`

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +public class HostDriverFixture {
Please use 4 spaces instead of 2 spaces as formatting.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +  Logger logger = LoggerFactory.getLogger(HostDriverFixture.class);
should be `private static final` and above the `Connection` variable

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +  Connection con;
Should be `private` and named `connection`

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +  public void connect(String s3270Path, String hostname, int port) {
Method needs to be annotated with `@FixtureMethod` in order to be seen by the test-editor.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +    logger.info("Host-Fixture starting ...");
A better log message would be `logger.info("Connecting to host='{}', port='{}' with s3270path='{}'", hostname, port, s3270path);`

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +      logger.info("Host-Fixture is not ready to rock :O(");
We should fail here, i.e. throw an exception

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +      logger.info("Host-Fixture ready to rock ;O)");
Better `successfully connected to host='{}', port='{}'`

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +    logger.info("Connection closing ...");
log message should appear after the logout and say something like "Successfully disconnected".

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +  public void getStatus() {
What is this used for? There is no return value.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +    logger.info("Set cursor position ...");
Log message should appear after the position is set and include the values.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/Locator.java
> +   * @param rol
useless javadoc in this class, please delete

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/Locator.java
> +
empty line

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/io/ErrorReader.java
> +    err = new BufferedReader(new InputStreamReader(process.getErrorStream()));
I don't see why the assignment to the instance variable is necessary here.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/io/ErrorReader.java
> +      while (true) {
There are better approaches of reading an input stream into a String.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/io/ErrorReader.java
> +public class ErrorReader extends Thread {
This class is never used so far.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +      logger.info("starting " + commandLine);
This is unreadable by a human without knowing the source code. There should be a better output for the user! Also the log level should be debug.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +      throw new RuntimeException("IO Exception while starting s3270/ws370.exe", ex);
The `s3270Path` would be useful to pass here instead of `s3270/ws370.exe`.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +      s3270Process.waitFor();
We could also use `waitFor(long timeout, TimeUnit unit)` here

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +  public void disconnect() {
The disconnect looks a bit confusing to me and should be rewritten. First, a quit command is sent to the process, afterwards it is destroyed and finally waited for its termination. A better way would be to send the quit command, wait for a certain timeout and if that doesn't occur kill the process. Also the cleanup logic is partly in this method, partly in the `cleanup()` method.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +    new Thread(new Runnable() {
I don't see why we need a separate thread here. Also with the comment above the sleeping might not be necessary.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +        } catch (final InterruptedException ex) {
The `InterruptedException` is thrown because of the sleeping. There is no need to duplicate the `destroy()` call in the catch block.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +      if (r.getStatus().matches(". . . C.*")) {
There should be a proper abstraction for the status String.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +        out.println("quit");
That's a bit suprising and a sideeffect. Why is the connection killed when the process is no longer connected?

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +  private void readOutput(List<String> lines) throws IOException {
The list should not be passed in as a parameter but be created by this method.

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +      logger.debug("---> \"{}\" entered ", command);
I would prefer: `("Command sent: {}", command`)

2017-05-17 13:04 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +  private void readOutput(List<String> lines) throws IOException {
Also why not use `in.lines().collect(Collectors::toList)`? logging should be done separately if the log level is debug.

2017-05-17 13:04 UTC, franzbecker commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +  public void connectionTest() {
That is a manual integration test, not a unit test.

2017-05-17 13:04 UTC, franzbecker commented on src/test/resources/log4j2.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Should use the same configuration as the other fixtures, see https://github.com/test-editor/rest-fixture/blob/develop/src/test/resources/log4j2.xml

2017-05-18 10:47 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +public class HostDriverFixture {
We should use Workspace Mechanics for harmonizing our code for the whole team members.

2017-05-18 11:21 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +    logger.info("Host-Fixture starting ...");
The connection method does that in the Connection Class when the s3270 process starts.

2017-05-18 11:27 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +    logger.info("Connection closing ...");
This is also done by the Connection

2017-05-18 11:33 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +  public void getStatus() {
The status will be handled in TE-497, the method getStatus() and typeInto() are connected to the not yet implemented methods with  "// TODO is coming next ;O)" statements in connection.getStatus() and connection.typeInto().

2017-05-18 11:36 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +    logger.info("Set cursor position ...");
same as above :-) Status will be implemented in next PullRequest same as typeInto()

2017-05-18 11:54 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +      logger.info("starting " + commandLine);
Totally agree with u. This will be implemented in TE-497

2017-05-18 11:57 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +      throw new RuntimeException("IO Exception while starting s3270/ws370.exe", ex);
?

2017-05-18 12:08 UTC, kbayraktar commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +  public void connectionTest() {
Yes we should discuss, how to test the host-fixture completely.

2017-06-07 14:16 UTC, franzbecker commented on settings.gradle
> +rootProject.name = 'hostfixture'
should be `host-fixture`

2017-06-07 14:16 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.aml
> +    template = "Connect to" ${hostname} "with path" s3270Path "and port" ${port}
I think hostname and port should be closer together, shouldn't they?
How about `"Connect to" ${hostname} "with port" ${port} "using s3270 from" ${s3270Path}`

2017-06-07 14:16 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +        return !connection.disconnect();
Should not be negated. `connection.disconnect()` should return true when the disconnect is successful.

2017-06-07 14:16 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/Locator.java
> +   * @return the col
useless comment, same as the other ones below

2017-06-07 14:16 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/Locator.java
> +   * @return the col
useless comment, same as the other ones below

2017-06-07 14:16 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +                        s3270Process.destroy();
duplicate here. The `InterruptedException` is only for the sleeping so it should wrap just the `Thread.sleep(...)`

2017-06-07 14:16 UTC, franzbecker commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +        assertEquals(hdf.connect(S2370_PATH, hostUrl, hostPort), true);
This just tests the mock.

2017-06-07 14:16 UTC, franzbecker commented on src/test/java/org/testeditor/fixture/host/integrationtest/HostDriverIntegrationTest.java
> +    // @Test
`@Test` is ok but you should add `@Ignore` instead - e.g. `@Ignore("manual execution only")`

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.aml
> +    template = "Connect to " ${hostname} " with path " s3270Path " and port " ${port}
should be ${s3270Path}  right?

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +        logger.info("Host-Fixture starting ...");
how about "connecting" instead of "starting"

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +        return connection.disconnect();
failing disconnect should raise exception (as connect does in case of failure)

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +        logger.info("Disconnected successfully from host : {} ", hostname);
successful even though I do not know whether isConnected is still true?

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +                    Thread.sleep(1000);
only sleep?

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +                out.println("quit");
code duplication with doQuit?

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +                s3270Process = null;
code duplication with cleanup?

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +            readOutput(lines);
why not return lines by calling readOutput ?

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +                Result result = new Result(lines.subList(0, size - 1), lines.get(size - 1));
why drop the list line? maybe put it into a separate method that describes why this is done?

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +    private void processAvailable() {
name suggests that bool is returned. Maybe use different name (e.g. assertProcessAvailable) ...

2017-06-12 11:58 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/s3270/Result.java
> +  private final List<String> data;
why not name this "lines"?

2017-06-12 12:44 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +                Result result = new Result(lines.subList(0, size - 1), lines.get(size - 1));
#ignore

2017-06-12 14:47 UTC, merged