TE-798 Type into implemented
test-editor/host-fixture pull request #3
Opened 2017-05-18 13:50 UTC by kbayraktar

2017-05-18 13:58 UTC, gunther-bachmann commented
DO NOT MERGE until feature/status is merged into develop. then merge into develop

2017-05-22 07:26 UTC, gunther-bachmann commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +    hdf.typeInto("äöüßabcdefg", STANDARD_ROW, STANDARD_COLUMN);
What exactly is tested here?

2017-05-22 07:26 UTC, gunther-bachmann commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
>      hdf.connect(S2370_PATH, hostUrl, hostPort);
This will probably fail on the build server, wouldn't it?

2017-05-22 07:26 UTC, gunther-bachmann commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
>      hdf.connect(S2370_PATH, hostUrl, hostPort);
why not have somthing like assumeTrue(hostDriverFixture.connected()); within the tests and check availibility of env parameters before actually attempting the connect here?

2017-05-22 07:26 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +    connection.doCommand("ascii"); // just to see if typed in successfully.
why not log this out if the output is of interest?

2017-05-22 07:26 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
>    public void typeInto(String value, int row, int col) {
Wouldn't 'typeAt' be more appropriate?

2017-05-22 07:26 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.aml
> +interaction type typeInto {
Wouldn't 'typeAt' be more appropriate?

2017-05-22 07:26 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.aml
> +    template = "Get Status"
Syntax conventions suggest "Get status"

2017-05-22 07:26 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +      logger.debug("---> Command sent: '{}'", command);
Aside from this we should talk about logging conventions in the team (syntax, level ...)

2017-05-22 07:26 UTC, gunther-bachmann commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +  private final String hostUrl = System.getenv("HOST_URL");
hostUrl should be HOST_URL, right?

2017-05-22 07:26 UTC, gunther-bachmann commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +  private final String S2370_PATH = System.getenv("S3270_PATH");
This should be S3270_PATH (typo)

2017-05-22 07:26 UTC, gunther-bachmann commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +  private final int hostPort = Integer.parseInt(System.getenv("HOST_PORT"));
Should be HOST_PORT, right?

2017-05-22 07:26 UTC, gunther-bachmann commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +  HostDriverFixture hdf;
why not name it 'hostDriverFixture', we don't use this variable too much, so the abbreviation does not help, does it?

2017-05-22 07:58 UTC, gunther-bachmann commented
By the way, is this TE issue number 798 really correct? Shouldn't it be 498?

2017-05-24 06:46 UTC, franzbecker commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +  private final String hostUrl = System.getenv("HOST_URL");
No it's not a constant.

2017-05-24 06:46 UTC, franzbecker commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
> +  private final String S2370_PATH = System.getenv("S3270_PATH");
Should be s3270Path as it's not a constant.

2017-06-14 13:19 UTC, franzbecker requested changes
Almost there, just a few minor changes

2017-06-14 13:19 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +     * parameters row an column.
typo: should be "and"

2017-06-14 13:19 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +     * are, the s3270 emulation will lock further actions.
Is there any way we can prevent that?

2017-06-14 13:19 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +            Thread.sleep(time); // 1000 milliseconds is one second.
the comment indicates that the time unit is confusing. Instead of the comment the parameter should be called `milliseconds`.

2017-06-14 13:19 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +            Thread.currentThread().interrupt();
Why? 😕

2017-06-14 13:19 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +     * @return true if disconnected succesful, false otherwise.
"successful" with 2 s

2017-06-14 13:19 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/HelperTool.java
> +public class HelperTool {
The name of this class is to generic

2017-06-14 13:19 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/HelperTool.java
> +            pathS3270 = s3270Path;
That's a pretty mean side-effect. You ask a question - is this path valid - and then change the internal static state 💣

2017-06-14 13:19 UTC, franzbecker commented on src/test/java/org/testeditor/fixture/host/HostDriverFixtureTest.java
>      String S3270_PATH = "S3270_PATH";
constants should be static and final

2017-06-14 13:19 UTC, franzbecker commented on src/main/java/org/testeditor/fixture/host/net/HelperTool.java
> +    public static boolean isOsWindows() {
There is already a  utility function for that. Why add it here? As I see it, it is only used in the test. No need to add it to production code then.

2017-06-14 13:50 UTC, kbayraktar commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +     * are, the s3270 emulation will lock further actions.
Not yet, therefore we need to have more experience with the s2370 driver.

2017-06-15 09:03 UTC, merged