Log levels adjusted.
test-editor/host-fixture pull request #30
Opened 2018-11-01 15:25 UTC by kbayraktar

2018-11-01 16:24 UTC, gunther-bachmann requested changes

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +        logger.debug("Host-Fixture connecting ...");
I'd add the parameters of the fixture method to the debug output

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +            logger.error("The connection to host '" + hostname + "' on port '" + port + "' could not be established.");
warn

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +        logger.trace("get Status ...");
debug

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +        logger.trace("Move cursor to position {} by {}.",elementLocator, locatorType );
debug level

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +        logger.trace("Generate all 3270-Fields on screen as String ...");
debug level

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
>          connection.connect(s3270Path, hostname, port, type, terminalMode, charSet, offset);
try catch and throw FixtureException

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +            logger.error("The connection to host '" + hostname + "' on port '" + port + "' could not be established.");
throw FixtureException instead of returning false

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +            logger.error("Something went wrong while creating screenshot for file {} :", filePath + filename );
warning would be better, right. the test may succeed ...

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +    // TODO Auto-generated method stub
remove todo, add something like
// do nothing
We could however think about writing screenshots here, too.

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +        // TODO Auto-generated method stub
see above

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +
see above

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/locators/LocatorByStart.java
> +            logger.error(columnExceptionMessage);
error logging is not necessary if throwing a fixture exception

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/locators/LocatorByStartStop.java
> +    public LocatorByStartStop(int startRow, int startColumn, int endRow, int endColumn, Status status, Offset offset) throws FixtureException {
no need for FixtureException

2018-11-01 16:24 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +            logger.error("Disconnection failed");
throw fixture exception instead of logging errors

2018-11-02 09:07 UTC, kbayraktar commented
Please Can you add these lines to build.gradle file:
```javascript
// For a summary of failed tests at the end of test execution.
tasks.withType(Test) {
    // a collection to track failedTests
    ext.failedTests = []
     afterTest { descriptor, result ->
        if (result.resultType == TestResult.ResultType.FAILURE) {
            String failedTest = "${descriptor.className}::${descriptor.name}"
            logger.debug("Adding " + failedTest + " to failedTests...")
            failedTests << [failedTest]
        }
    }
     afterSuite { suite, result ->
        if (!suite.parent) { // will match the outermost suite
            // logs each failed test
            if (!failedTests.empty) {
                logger.lifecycle("\n\n*************************************************************************************************")
                logger.lifecycle("\nFailed tests:")
                failedTests.each { failedTest ->
                    logger.lifecycle("${failedTest}")
                }
            }
            logger.lifecycle("\n*************************************************************************************************\n")
        }
    }
}
```

2018-11-05 13:20 UTC, gunther-bachmann requested changes

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +     *            <br>CADIR : Specifies a directory containing CA (root) certificates to use when verifying a certificate provided by the host. (OpenSSL only).
prefix with 'HOSTFIXTURE_'

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +            throw new FixtureException(e.getMessage(), FixtureException.keyValues("elementlocator", elementLocator,
pass e as parameter

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/HostDriverFixture.java
> +            throw new FixtureException(e.getMessage(), FixtureException.keyValues("elementlocator", elementLocator,
pass e as parameter to FixtureException

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/locators/LocatorByStartStop.java
>       * @throws FixtureException
@throws is no longer valid

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +        }else {
return buffer.toString();

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +            commandLine = commandLine + " -noverifycert";
return commandLine + " -noverifycert";

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +        return commandLine;
remove this line

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +            logger.error("Something went wrong during termination of s3270 process");
should be warning

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/net/Connection.java
> +            logger.error("Something went wrong during closing InputStreamreader of s3270 process");
warning

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/util/LineReader.java
> +                throw new RuntimeException(
IllegalArgument?

2018-11-05 13:20 UTC, gunther-bachmann commented on src/main/java/org/testeditor/fixture/host/util/LineReader.java
> +            throw new RuntimeException("Your chosen argument width '" + locator.getWidth()
IllegalArgument?

2018-11-05 16:37 UTC, gunther-bachmann approved these changes

2018-11-05 16:37 UTC, merged